---
- name: install and launch metricbeat
  hosts: webservers
  become: true
  tasks:
          - name: download metricbeat
            command: 'curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb'

          - name: install metricbeat
            command: 'dpkg -i metricbeat-7.4.0-amd64.deb'

          - name: copy metricbeat.yml to webservers
            copy:
                    src: /etc/ansible/metricbeat-config.yml
                    dest: /etc/metricbeat/metricbeat.yml

          - name: enable docker module
            command: 'sudo metricbeat modules enable docker'

          - name: setup metricbeat
            command: 'sudo metricbeat setup -e'

          - name: run metricbeat
            command: 'sudo service metricbeat start'

          - name: enable metricbeat on boot
            systemd:
                    name: metricbeat
                    state: started
                    enabled: yes

